  # TODO Build an automation for the yeelight to cycle through colors when the dimmer switches are pressed

  # Connected Remotes
  - alias: 'Turn on master lights from remote'
    trigger:
      platform: template
      value_template: "{{ is_state_attr('binary_sensor.master_bedroom', 'button_on_pressed', true) }}"
    action:
      - service: light.turn_on
        entity_id: group.master_lights
  - alias: 'Turn off master lights from remote'
    trigger:
      platform: template
      value_template: "{{ is_state_attr('binary_sensor.master_bedroom', 'button_off_pressed', true) }}"
    action:
      - service: light.turn_off
        entity_id: group.master_lights
  - alias: 'Turn on office lights from remote'
    trigger:
      platform: template
      value_template: "{{ is_state_attr('binary_sensor.office', 'button_on_pressed', true) }}"
    action:
      - service: light.turn_on
        entity_id: group.office_lights
  - alias: 'Turn off office lights from remote'
    trigger:
      platform: template
      value_template: "{{ is_state_attr('binary_sensor.office', 'button_off_pressed', true) }}"
    action:
      - service: light.turn_off
        entity_id: group.office_lights
  - alias: 'Turn on garage lights from remote'
    trigger:
      platform: template
      value_template: "{{ is_state_attr('binary_sensor.garage', 'button_on_pressed', true) }}"
    action:
      - service: light.turn_on
        entity_id: group.garage_lights
  - alias: 'Turn off garage lights from remote'
    trigger:
      platform: template
      value_template: "{{ is_state_attr('binary_sensor.garage', 'button_off_pressed', true) }}"
    action:
      - service: light.turn_off
        entity_id: group.garage_lights
  - alias: 'Turn on basement lights from remote'
    trigger:
      platform: template
      value_template: "{{ is_state_attr('binary_sensor.basement', 'button_on_pressed', true) }}"
    action:
      - service: light.turn_on
        entity_id: group.basement_lights
  - alias: 'Turn off basement lights from remote'
    trigger:
      platform: template
      value_template: "{{ is_state_attr('binary_sensor.basement', 'button_off_pressed', true) }}"
    action:
      - service: light.turn_off
        entity_id: group.basement_lights
  - alias: 'Turn on livingroom lights from remote'
    trigger:
      platform: template
      value_template: "{{ is_state_attr('binary_sensor.living_room', 'button_on_pressed', true) }}"
    action:
      - service: light.turn_on
        entity_id: group.livingroom_lights
  - alias: 'Turn off livingroom lights from remote'
    trigger:
      platform: template
      value_template: "{{ is_state_attr('binary_sensor.living_room', 'button_off_pressed', true) }}"
    action:
      - service: light.turn_off
        entity_id: group.livingroom_lights

  # NPR
  - alias: Play NPR in the morning
    trigger:
      platform: time
      at: '06:30:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.ian_ians_phone
          state: 'home'
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
    action:
      - service: media_player.turn_on
        data:
          entity_id: media_player.upper_main_floor
      - service: media_player.volume_set 
        data:
          entity_id: media_player.upper_main_floor
          volume_level: .20
      - delay: '00:00:30'
      - service: media_player.play_media
        data:
          entity_id: media_player.upper_main_floor
          media_content_id: http://18243.live.streamtheworld.com:3690/KIOSFM_SC
          media_content_type: audio/mp3
  - alias: Play NPR in the morning on weekends
    trigger:
      platform: time
      at: '08:00:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.ian_ians_phone
          state: 'home'
        - condition: time
          weekday:
            - sat
            - sun
    action:
      - service: media_player.turn_on
        data:
          entity_id: media_player.upper_main_floor
      - service: media_player.volume_set 
        data:
          entity_id: media_player.upper_main_floor
          volume_level: .20
      - delay: '00:00:30'
      - service: media_player.play_media
        data:
          entity_id: media_player.upper_main_floor
          media_content_id: http://18243.live.streamtheworld.com:3690/KIOSFM_SC
          media_content_type: audio/mp3

###################################
##  cuckoo Clock simulation.
## Plays the number of cuckoos per hour and 1 on the half hour.
###################################
  - alias: Cuckoo Clock
    trigger:
      - platform: time
        minutes: 00
        seconds: 00
    condition:
      - condition: time
        after: '09:00:00'
        before: '23:00:00'
      - condition: template
        value_template: >
          {% if is_state('media_player.living_room_speakers', 'playing') %} #TODO Check whole house, main floor and upper main floor as well
            false
          {% else %}
            true
          {% endif %}
    action:
      - service: media_player.turn_on
        entity_id: media_player.living_room_speakers
      - service: media_player.volume_set
        entity_id:
          - media_player.living_room_speakers
        data:
          volume_level: 0.20
      - service: media_player.play_media
        data_template:
          entity_id:
            - media_player.living_room_speakers
          media_content_id: https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/sounds/cuckoo-clock-{{now().strftime("%I")}}.wav
          media_content_type: audio/mp4
  - alias: Chelsea left home # TODO Don't do this at night
    trigger:
      - platform: state
        entity_id: device_tracker.chelsea_chelseas_phone
        from: 'home'
        to: 'not_home'
        for:
          minutes: 5
    action:
      - service: notify.ian
        data:
          message: "Chelsea just left home at {{ now() }}"
  - alias: Basement Home Volume
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_number.basement_home_volume
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.basement_home
          volume_level: '{{ states.input_number.basement_home_volume.state }}'
  - alias: Keep Basement Home Volume Slider in Sync
    hide_entity: True
    trigger:
      platform: state
      entity_id: media_player.basement_home
    action:
      service: input_number.select_value
      data_template:
        entity_id: input_number.basement_home_volume
        value: "{{states.media_player.playroom.attributes.volume_level | multiply (100) | int}}"
  - alias: Office Home Volume
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_number.office_home_volume
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.office_home
          volume_level: '{{ states.input_number.office_home_volume.state }}'
  - alias: Keep Office Home Volume Slider in Sync
    hide_entity: True
    trigger:
      platform: state
      entity_id: media_player.office_home
    action:
      service: input_number.select_value
      data_template:
        entity_id: input_number.office_home_volume
        value: "{{states.media_player.playroom.attributes.volume_level | multiply (100) | int}}"
  - alias: Ktichen Home Volume
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_number.kitchen_home_volume
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.kitchen_home
          volume_level: '{{ states.input_number.kitchen_home_volume.state }}'
  - alias: Keep Kitchen Home Volume Slider in Sync
    hide_entity: True
    trigger:
      platform: state
      entity_id: media_player.kitchen_home
    action:
      service: input_number.select_value
      data_template:
        entity_id: input_number.kitchen_home_volume
        value: "{{states.media_player.playroom.attributes.volume_level | multiply (100) | int}}"
  - alias: Living Room Home Volume
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_number.living_room_home_volume
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.living_room_home
          volume_level: '{{ states.input_number.living_room_home_volume.state }}'
  - alias: Keep Living Room Home Volume Slider in Sync
    hide_entity: True
    trigger:
      platform: state
      entity_id: media_player.living_room_home
    action:
      service: input_number.select_value
      data_template:
        entity_id: input_number.living_room_home_volume
        value: "{{states.media_player.playroom.attributes.volume_level | multiply (100) | int}}"
  - alias: Master Home Volume
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_number.master_home_volume
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.master_home
          volume_level: '{{ states.input_number.master_home_volume.state }}'
  - alias: Keep Master Home Volume Slider in Sync
    hide_entity: True
    trigger:
      platform: state
      entity_id: media_player.master_home
    action:
      service: input_number.select_value
      data_template:
        entity_id: input_number.master_home_volume
        value: "{{states.media_player.playroom.attributes.volume_level | multiply (100) | int}}"
  - alias: Shop Home Volume
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_number.shop_home_volume
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.shop_home
          volume_level: '{{ states.input_number.shop_home_volume.state }}'
  - alias: Keep Shop Home Volume Slider in Sync
    hide_entity: True
    trigger:
      platform: state
      entity_id: media_player.shop_home
    action:
      service: input_number.select_value
      data_template:
        entity_id: input_number.shop_home_volume
        value: "{{states.media_player.playroom.attributes.volume_level | multiply (100) | int}}"

  # # Keep Google Home Alive
  # - alias: Keep Office Home Alive
  #   hide_entity: True
  #   trigger:
  #     platform: time
  #     minutes: '/2'
  #     seconds: 00
  #   condition:
  #     - condition: template
  #       value_template: >
  #         {% if is_state('media_player.whole_house', 'playing') %}
  #           false
  #         {%-elif is_state('media_player.main_floor', 'playing') %}
  #           false
  #         {%-elif is_state('media_player.office_home', 'playing') %}
  #           false
  #         {% else %}
  #           true
  #         {% endif %}
  #   action:
  #     service: media_player.play_media
  #     entity_id: media_player.office_home
  #     data:
  #       media_content_id: https://hassio.local:8123/local/1sec.mp3
  #       media_content_type: music